x-defaults-enzyme:
  &default-dev-settings
  hostname: ${ENZYME_CONTAINER_HOSTNAME}
  tty: true

x-defaults-build:
  &default-build-args
  args:
    - BASE_DOCKER_REPO=${DOCKER_HUB_REPO}
    - BASE_TAG=${TAG}
    - UBUNTU_VERSION=${CONTAINER_UBUNTU_VERSION}
    - USERNAME=${CONTAINER_USERNAME}
    - PASSWORD=${CONTAINER_PASSWORD}
    - UID=${CONTAINER_UID}
    - TIMEZONE=${CONTAINER_TIMEZONE}
    - USER_PRIVILEGE_LEVEL=root

services:
  enzyme:
    << : *default-dev-settings
    build:
      context: ./build
      << : *default-build-args
    image: ${DOCKER_HUB_REPO}:${TAG}-enzyme
    container_name: enzyme
    tty: true
